DROP ROLE IF EXISTS admin;
DROP ROLE IF EXISTS manager;
DROP ROLE IF EXISTS customer;

CREATE ROLE admin
CREATE ROLE manager
CREATE ROLE customer

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
